### ISSUE TITLE
mybatis plus generator 3.5.3 strategyConfig 无 fileOverride 配置

### ISSUE THREAD

**Issue by yishiyouya** [baomidou/awesome-mybatis-plus#5]
mybatis plus generator 3.5.3 strategyConfig 无 fileOverride配置
详情：
       备注提示， 全局配置 fileOverride 已迁移到策略配置。
但是 策略配置 中未找到 fileOverride。
![image](https://user-images.githubusercontent.com/9388966/200464115-5d11d19b-e429-41e6-83dd-6a0e57815983.png)
![image](https://user-images.githubusercontent.com/9388966/200464323-0bdcf38e-2d8f-4884-9fd9-de877d116110.png)

**Comment by qmdx** [comment]
https://baomidou.com/ 查看代码生成器部分文档
